### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by armzajr**
Thk

### CODE REVIEW

**Comment by armzajr** [comment]
Thk

**Comment by armzajr** [comment]
dd

**Comment by armzajr** [comment]
etggg

**Comment by Bluscream** [comment]
hm?

**Review by Kroshboy — APPROVED** [review]

**Comment by Kroshboy** [comment]
g

**Comment by lopepalos** [comment]
71a64dab4ccf422fa8709b81f91d2835989e66b9

**Review by Bluscream — CHANGES_REQUESTED** [review]
nope

**Pull request closed without merging**
